import React, { useEffect, useState } from "react";
import { GetServerSideProps } from "next";
import { fetchClient, fetchServer } from "@/services/auth";

import Calendar from "react-calendar";

import {
  Popover,
  PopoverTrigger,
  PopoverContent,
  Pagination,
} from "@nextui-org/react";

// Generated by https://quicktype.io

interface Response {
  totalItems: number;
  results: Submission[];
  totalPages: number;
  currentPage: number;
}

interface Submission {
  id: number;
  price: number;
  paymentDate: string;
  Agreement: Agreement;
}

interface Agreement {
  id: number;
  terms: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  SupplierId: number;
  BuyerId: number;
  Buyer: Buyer;
}

export interface Buyer {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
}

export const getServerSideProps: GetServerSideProps<{}> = async (context) => {
  return {
    props: {},
  };
};

type ValuePiece = Date | null;

type Value = ValuePiece;

import "react-calendar/dist/Calendar.css";
import "react-date-picker/dist/DatePicker.css";
import DatePicker from "react-date-picker";
import { PageTitle, Title } from "@/components/Text";
import { Button } from "@/components/Form";
import BuyerCard from "@/components/Card/Buyer";

const BestBuyers = () => {
  const [startDate, setStartDate] = useState<Date>(new Date());
  const [endDate, setEndDate] = useState<Date>(new Date());

  const [response, setResponse] = useState<Response>();
  const [page, setPage] = useState<number>(0);
  const [error, setError] = useState<string>("");

  const handleSubmit = async (page: string) => {
    const query = new URLSearchParams({
      start: startDate.toISOString(),
      end: endDate.toISOString(),
      size: "3",
      page,
    });

    const response = await fetchClient(
      `/admin/best-buyers?${query.toString()}`,
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    if (response.status !== 200) {
      const error = await response.json();
      setError(error.message || "Unknown error");
      return;
    }

    const data = await response.json();
    setResponse(data);
  };

  useEffect(() => {
    if (page === 0) return;
    handleSubmit((page - 1).toString());
  }, [page]);

  return (
    <div>
      <PageTitle className="mb-2">Best buyers</PageTitle>

      <div className="flex left-0 gap-5">
        <div className="flex gap-2 items-center">
          <p>Start date:</p>
          <DatePicker
            onChange={(value) => setStartDate(value || (new Date() as any))}
            value={startDate}
          />
        </div>

        <div className="flex gap-2 items-center">
          <p>End date:</p>
          <DatePicker
            onChange={(value) => setEndDate(value || (new Date() as any))}
            value={endDate}
          />
        </div>

        <Button className="w-max" onClick={() => handleSubmit("0")}>
          Search
        </Button>
        <Button className="w-max" onClick={() => setResponse(undefined)}>
          Clear filters
        </Button>
      </div>

      <PageTitle className="mt-5 text-lg">Results</PageTitle>
      {error && <p className="text-red-500">{error}</p>}
      {!error && response && response.results.length > 0 && (
        <div className="flex flex-col gap-5">
          <div className="inline-flex gap-4">
            {response.results.map((result) => {
              return (
                <BuyerCard
                  key={result.id}
                  buyer={result.Agreement.Buyer}
                  submission={result as any}
                />
              );
            })}
          </div>
          <Pagination
            onChange={setPage}
            page={page}
            total={response.totalPages}
          />
        </div>
      )}
    </div>
  );
};

export default BestBuyers;
