import NextAuth from "next-auth";
import { DefaultSession } from "next-auth";
import { DefaultJWT } from "next-auth/jwt";

// Generated by https://quicktype.io

export interface AppUser {
  id: number;
  firstName: string;
  lastName: string;
  profession: string;
  email: string;
  type: "buyer" | "supplier";
  admin: boolean;
  accessToken: string;
}

declare module "next-auth" {
  interface JWT {
    id: number;
  }

  interface Session {
    user: AppUser;
  }
}
