// Create a page to display the user's agreements. Fetch data from the /agreements API.

import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { getServerSession } from "next-auth";
import React from "react";
import { authOptions } from "./api/auth/[...nextauth]";
import { fetchServer } from "@/services/auth";
import AgreementCard from "@/components/Card/Agreement";

// Generated by https://quicktype.io

export interface Agreement {
  id: number;
  terms: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  SupplierId: number;
  BuyerId: number;
}

export const getServerSideProps: GetServerSideProps<{
  agreements: Agreement[];
}> = async (context) => {
  const res = await fetchServer(
    "/agreements",
    {
      method: "GET",
    },
    context
  );

  const data = await res.json();

  return {
    props: {
      agreements: data,
    },
  };
};

const Agreements = ({
  agreements,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <h1 className="text-2xl font-bold mb-3">Active agreements</h1>
      <div className="inline-flex gap-4 z-0">
        {agreements.map((agreements) => {
          return <AgreementCard key={agreements.id} {...agreements} />;
        })}
      </div>
      {/* <h1 className="text-2xl font-bold my-3">All submissions</h1> */}
    </>
  );
};

export default Agreements;
