// Create a page to display the user's agreements. Fetch data from the /agreements API.

import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { getServerSession } from "next-auth";
import React from "react";
import { authOptions } from "./api/auth/[...nextauth]";
import { fetchServer } from "@/services/auth";

// Generated by https://quicktype.io

export interface Agreement {
  id: number;
  terms: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  SupplierId: number;
  BuyerId: number;
}

export const getServerSideProps: GetServerSideProps<{
  agreements: Agreement[];
}> = async (context) => {
  const res = await fetchServer(
    "/agreements",
    {
      method: "GET",
    },
    context
  );

  const data = await res.json();

  return {
    props: {
      agreements: data,
    },
  };
};

const Agreements = ({
  agreements,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return <pre>{JSON.stringify(agreements, null, 2)}</pre>;
};

export default Agreements;
